name: websockets-mqtt-visualizer
version: '0.1'
summary: Visualize MQTT data over WebSockets
description: |
  A web-app that visualizes data from an MQTT connection to a web clients by
  sending the data over WebSockets directly

grade: stable
confinement: strict

parts:
  my-part:
    plugin: go
    source: go-code
    build-snaps: [go]
    go-importpath: github.com/anonymouse64/websockets-mqtt-visualizer
    build-packages: [build-essential, gcc]
