name: iot-data-plotter
version: "0.1"
summary: Visualize IoT data in a browser
description: |
  A configurable webserver that visualizes data from various IoT sources to 
  web clients by gathering the data and then sending the data to a web browser
  using WebSockets to live plot the data as it's sent, without a static 
  database storing the data. 

grade: stable
confinement: strict

apps:
  server:
    command: bin/server -c $SNAP_DATA/config.toml
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  server:
    plugin: dump
    source: .
    build-packages: [build-essential, gcc]
    build-snaps: [go]
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      case $SNAPCRAFT_ARCH_TRIPLET in
        arm-linux-*)
          export GOARCH=arm
          export GOARM=7
          ;;
        x86_64*)
          export GOARCH=amd64
          ;;
        # TODO add other arches
      esac
      GO111MODULE=on go build -o $SNAPCRAFT_PART_INSTALL/bin/server cmd/server/main.go
  html-assets:
    plugin: dump
    source: .
    prime: [static/*, templates/*]
