name: websockets-mqtt-visualizer
version: '0.1'
summary: Visualize MQTT data over WebSockets
description: |
  A web-app that visualizes data from an MQTT connection to a web clients by
  sending the data over WebSockets directly

grade: stable
confinement: strict

parts:
  server:
    plugin: dump
    source: .
    build-packages: [build-essential, gcc]
    build-snaps: [go]
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      case $SNAPCRAFT_ARCH_TRIPLET in
        arm-linux-*)
          export GOARCH=arm
          export GOARM=7
          ;;
        x86_64*)
          export GOARCH=amd64
          ;;
        # TODO add other arches
      esac
      GO111MODULE=on go build -o $SNAPCRAFT_PART_INSTALL/bin/server cmd/server/main.go
  html-assets:
    plugin: dump
    source: .
    prime: [static/*, templates/*]
